// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFh2xzfTmNZDcElmIyyydwloQS0L3pkI8',
    appId: '1:494373224419:web:b762b8ad322d119d48aad6',
    messagingSenderId: '494373224419',
    projectId: 'bloodshare-4440f',
    authDomain: 'bloodshare-4440f.firebaseapp.com',
    storageBucket: 'bloodshare-4440f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQtWr9oHVcW5TTn5rYhcWjnhzjEn0vdm8',
    appId: '1:494373224419:android:efc4c24736035cad48aad6',
    messagingSenderId: '494373224419',
    projectId: 'bloodshare-4440f',
    storageBucket: 'bloodshare-4440f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUe6dgkBJT9xG5ZhAhNs7uW57XXeeckI8',
    appId: '1:494373224419:ios:89e405ba3c5eecb048aad6',
    messagingSenderId: '494373224419',
    projectId: 'bloodshare-4440f',
    storageBucket: 'bloodshare-4440f.firebasestorage.app',
    iosBundleId: 'com.example.bloodshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUe6dgkBJT9xG5ZhAhNs7uW57XXeeckI8',
    appId: '1:494373224419:ios:89e405ba3c5eecb048aad6',
    messagingSenderId: '494373224419',
    projectId: 'bloodshare-4440f',
    storageBucket: 'bloodshare-4440f.firebasestorage.app',
    iosBundleId: 'com.example.bloodshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFh2xzfTmNZDcElmIyyydwloQS0L3pkI8',
    appId: '1:494373224419:web:ec4665fbcf98f14f48aad6',
    messagingSenderId: '494373224419',
    projectId: 'bloodshare-4440f',
    authDomain: 'bloodshare-4440f.firebaseapp.com',
    storageBucket: 'bloodshare-4440f.firebasestorage.app',
  );
}
